apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modeldeployments.robotics.idp
spec:
  group: robotics.idp
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              modelName:
                type: string
                description: "Name of the ML model"
              modelUri:
                type: string
                description: "URI to model artifacts (S3, GCS, etc.)"
              modelFormat:
                type: string
                enum: ["tensorflow", "pytorch", "onnx", "tensorrt", "openvino"]
              version:
                type: string
                description: "Model version"
              targetRobots:
                type: object
                properties:
                  selector:
                    type: object
                    properties:
                      matchLabels:
                        type: object
                        additionalProperties:
                          type: string
                      matchExpressions:
                        type: array
                        items:
                          type: object
                  percentage:
                    type: integer
                    minimum: 1
                    maximum: 100
              deploymentStrategy:
                type: object
                properties:
                  type:
                    type: string
                    enum: ["rolling", "canary", "blue-green"]
                  canaryPercentage:
                    type: integer
                    minimum: 1
                    maximum: 100
              resourceRequirements:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  gpu:
                    type: boolean
                  minReplicas:
                    type: integer
                  maxReplicas:
                    type: integer
              monitoring:
                type: object
                properties:
                  enableMetrics:
                    type: boolean
                  customMetrics:
                    type: array
                    items:
                      type: string
              rollback:
                type: object
                properties:
                  enabled:
                    type: boolean
                  conditions:
                    type: array
                    items:
                      type: object
                      properties:
                        metric:
                          type: string
                        threshold:
                          type: string
                        operator:
                          type: string
                          enum: [">", "<", ">=", "<=", "==", "!="]
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Deploying", "Ready", "Failed", "RollingBack"]
              replicas:
                type: object
                properties:
                  desired:
                    type: integer
                  ready:
                    type: integer
                  updated:
                    type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
              deploymentHistory:
                type: array
                items:
                  type: object
                  properties:
                    version:
                      type: string
                    deployedAt:
                      type: string
                      format: date-time
                    status:
                      type: string
        required:
        - spec
    additionalPrinterColumns:
    - name: Model
      type: string
      jsonPath: .spec.modelName
    - name: Version
      type: string
      jsonPath: .spec.version
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Ready
      type: string
      jsonPath: .status.replicas.ready
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: modeldeployments
    singular: modeldeployment
    kind: ModelDeployment
