apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: robotprofiles.robotics.idp
spec:
  group: robotics.idp
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              robotId:
                type: string
                description: "Unique identifier for the robot"
              hardware:
                type: object
                properties:
                  cpu:
                    type: object
                    properties:
                      cores:
                        type: integer
                      architecture:
                        type: string
                        enum: ["x86_64", "arm64", "armv7"]
                  memory:
                    type: object
                    properties:
                      total:
                        type: string
                      available:
                        type: string
                  gpu:
                    type: object
                    properties:
                      present:
                        type: boolean
                      model:
                        type: string
                      memory:
                        type: string
                  sensors:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: ["camera", "lidar", "imu", "gps", "ultrasonic"]
                        model:
                          type: string
                        topic:
                          type: string
              capabilities:
                type: array
                items:
                  type: string
                  enum: ["navigation", "manipulation", "vision", "ml_inference"]
              constraints:
                type: object
                properties:
                  maxBatteryConsumption:
                    type: string
                  operatingEnvironment:
                    type: string
                    enum: ["indoor", "outdoor", "warehouse", "manufacturing"]
              location:
                type: object
                properties:
                  zone:
                    type: string
                  coordinates:
                    type: object
                    properties:
                      x:
                        type: number
                      y:
                        type: number
                      z:
                        type: number
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Active", "Inactive", "Maintenance"]
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              lastSeen:
                type: string
                format: date-time
              batteryLevel:
                type: integer
                minimum: 0
                maximum: 100
        required:
        - spec
    additionalPrinterColumns:
    - name: Robot ID
      type: string
      jsonPath: .spec.robotId
    - name: Status
      type: string
      jsonPath: .status.phase
    - name: Battery
      type: integer
      jsonPath: .status.batteryLevel
    - name: Last Seen
      type: string
      jsonPath: .status.lastSeen
  scope: Cluster
  names:
    plural: robotprofiles
    singular: robotprofile
    kind: RobotProfile
