apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: roboticsapplications.robotics.idp
spec:
  group: robotics.idp
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              appName:
                type: string
                description: "Name of the robotics application"
              image:
                type: string
                description: "Container image for the application"
              version:
                type: string
                description: "Application version"
              targetRobots:
                type: object
                properties:
                  selector:
                    type: object
                    properties:
                      matchLabels:
                        type: object
                        additionalProperties:
                          type: string
                      matchExpressions:
                        type: array
                        items:
                          type: object
              resourceRequirements:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  storage:
                    type: string
              configuration:
                type: object
                properties:
                  env:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                  configMaps:
                    type: array
                    items:
                      type: string
                  secrets:
                    type: array
                    items:
                      type: string
              networking:
                type: object
                properties:
                  ports:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        port:
                          type: integer
                        protocol:
                          type: string
                          enum: ["TCP", "UDP"]
              healthChecks:
                type: object
                properties:
                  livenessProbe:
                    type: object
                    properties:
                      httpGet:
                        type: object
                        properties:
                          path:
                            type: string
                          port:
                            type: integer
                      initialDelaySeconds:
                        type: integer
                      periodSeconds:
                        type: integer
                  readinessProbe:
                    type: object
                    properties:
                      httpGet:
                        type: object
                        properties:
                          path:
                            type: string
                          port:
                            type: integer
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Failed", "Succeeded"]
              replicas:
                type: object
                properties:
                  desired:
                    type: integer
                  ready:
                    type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
        required:
        - spec
    additionalPrinterColumns:
    - name: App Name
      type: string
      jsonPath: .spec.appName
    - name: Version
      type: string
      jsonPath: .spec.version
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Ready
      type: string
      jsonPath: .status.replicas.ready
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: roboticsapplications
    singular: roboticsapplication
    kind: RoboticsApplication
